# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: NPM Install
        run: npm install

      - name: Build EXE
        run: npm run dist

      - name: Copy Installer
        run: copy "dist\Nader WIX Testing Setup 1.0.1.exe" wix\installer.exe

      - name: Check WIX
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          light.exe

      - name: Make Installer
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          cd wix
          candle.exe installer.wxs -ext WixUtilExtension
          light.exe installer.wixobj -ext WixUtilExtension

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: wix\installer.msi
          retention-days: 1
